springdoc:
  swagger-ui:
    path: swagger
    try-it-out-enabled: true
    filter: true
    operations-sorter: method
    display-request-duration: true
#    supported-submit-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH, TRACE
#    enabled: false
#    query-config-enabled: false
#  api-docs:
#    enabled: false

spring:
  application:
    name: DeepLung

  jackson:
    time-zone: Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deeplung?serverTimezone=Asia/Seoul
    username: root
    password: ohw62459930!
  #    url: jdbc:mysql://jangburich.cbu4ao0sslpa.ap-northeast-2.rds.amazonaws.com:3306/jangburich?serverTimezone=Asia/Seoul
  #      username: admin
  #      password: jangburich!
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: 7dc99f011b193840a4366ee564a24b8b49f46182db7da914772761c547b0569dfdba1e376ab1218dca2b9c055bcc48fdbee8ce95f52a214778a26582bbd72ff4
    access:
      expiration: 900000
    refresh:
      expiration: 604800000

logging.level:
  org.hibernate.SQL: debug